Supply Compose With More Permissive Type, fixes #13
markhobson/hamcrest-compose pull request #18
Opened 2018-01-05 17:37 UTC by Megamiun

Hey, I has some problems with generics types and couldn't make a `compose` method which accepted both `Iterable<Matcher<? super T>>` and `Iterable<Matcher<T>>`, so to avoid breaking the tests of people whom used `Iterable<Matcher<T>>`, I added a method called `composes` with this change on signature.

If there is no problem breaking compatibility, you can simply remove the `compose(Iterable<Matcher<T>>)` and change it to my new methods.

It is a change that I think will only affect a minority of the users as type inference will take care of it most of times, but even so, I think the choice is yours about this decision.

PS: I changed the varargs methods with the `? super T`, but only because it will not break anyone tests, as it has been added to the repository yesterday.

2018-01-05 21:07 UTC, markhobson commented
Thanks for the PR. I'm happy to change the existing `compose(Iterable<Matcher<T>>)` to `compose(Iterable<Matcher<? super T>>)` as the API isn't stable yet.

2018-01-26 13:39 UTC, Megamiun commented
Hello, @markhobson, about this PR, do you have an idea of when it will be merged and updated on Maven Central Repository? I did it with some helper classes, but it would be so better to have that out of the box.

Thank you

2018-01-26 14:21 UTC, markhobson commented
Hi, sorry I thought you were going to update the PR from my feedback?

On 26 Jan 2018 13:39, "Gabryel Monteiro" <notifications@github.com> wrote:

> Hello, @markhobson <https://github.com/markhobson>, about this PR, do you
> have an idea of when it will be merged and updated on Maven Central
> Repository? I did it with some helper classes, but it would be so better to
> have that out of the box.
>
> Thank you
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/markhobson/hamcrest-compose/pull/18#issuecomment-360786857>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAK5C1kPM3k4pz6tbtReA_YD5oYYHg--ks5tOdWUgaJpZM4RUu2c>
> .
>

2018-01-26 14:37 UTC, Megamiun commented
Oh, sorry, so I can change the signature of the method here? Ok, I thought you would change it, just a minute that I will update the PR!

2018-01-26 14:51 UTC, Megamiun commented
Here, sorry for the delay and confusion!

2018-01-29 21:04 UTC, markhobson commented
No probs, thanks! I'll review it now.

2018-01-29 21:19 UTC, markhobson requested changes
Could you also squash all the commits on this PR please?

2018-01-29 21:19 UTC, markhobson commented on main/src/main/java/org/hobsoft/hamcrest/compose/ComposeMatchers.java
> +	private static <E> List<Matcher<? super E>> toSuperList(Iterable<Matcher<E>> iterable)
Don't think we need this method now.

2018-01-29 21:19 UTC, markhobson commented on main/src/test/java/org/hobsoft/hamcrest/compose/ComposeMatchersTest.java
> +	public void composeWithMatchersListReturnsMatcher()
Looks like a duplicate of `composeWithMatcherListReturnsMatcher`? Be worth replacing with a `composeWithSupertypeMatcherListReturnsMatcher` test.

2018-01-30 13:36 UTC, Megamiun commented
Ok, now I think everything is alright, @markhobson. And yes, sorry for the previous leftovers of my change hahahah

2018-01-30 20:53 UTC, merged

2018-01-30 20:54 UTC, markhobson commented
Thanks @Megamiun! Applied and improved the supertype matcher tests.

2018-01-31 00:23 UTC, Megamiun commented
Oh, saw the changes. Really good, loved them. I'm really an amateur on tests and your examples will help me to make better tests. Thanks too, @markhobson.

Oh, and talking about that, is there any prediction(I am no certain this is the right word, english isn't my native language) to have an update in Maven Central repo with those changes?

2018-01-31 07:27 UTC, markhobson commented
No probs, glad to help! I've just released 0.4.0 so it should appear in Maven Central shortly.